title: Climate, GIS & DRM Resource Hub
description: A curated hub of resources in climate change, GIS, disaster risk management, and sustainability.
theme: just-the-docs

url: https://ynx23.github.io/

plugins:
  - jekyll-default-layout
